# Site settings
title: News Releases - RDFa Lite
email: plansmash@me.com
baseurl: "/news-rdfa"
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8
host: localhost